# This workflow will do a clean install of node dependencies,
# build the source code and run tests.
# see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test, build and deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.16.x]
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --production=false --frozen-lockfile
      - name: Run linter
        run: find ./src -type f | egrep '\.js$' | tr '\n' '\0' | xargs -0 yarn eslint
      - name: Run tests
        run: CI=true yarn test
      - name: Build app
        run: yarn build
      - name: Deploy app
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=./build
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
